[package]
name = "player"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ausha"
path = "src/main.rs"

[dependencies]
ausha-core = { path = "../core" }
serde_json = "1"
getrandom = "0.3"
libc = "0.2.189"
mdns-sd = { version = "0.21.1", default-features = false }
qrcode = { version = "0.14.1", default-features = false }

[dev-dependencies]
image = "0.25.10"
rqrr = "0.11.0"
