[package]
name = "ausha-receiver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Play audio from an Ausha sender on the local network"

[[bin]]
name = "ausha-recv"
path = "src/main.rs"

[dependencies]
ausha-client = { path = "../client" }
